language: rust

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - CLIPPY_TOOLCHAIN=nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8

before_script:
  - if [ $TRAVIS_RUST_VERSION = $CLIPPY_TOOLCHAIN ]; then rustup component add clippy-preview --toolchain=$CLIPPY_TOOLCHAIN; fi
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

script: ./test.sh
